SYSTEM:
  NUM_GPU: 1
  NUM_CPU: 4
MODEL:
  N_RESBLOCKS: 20
  N_RESGROUPS: 10
  BLOCK_TYPE: rcan_block
  PLANES: 64
  SE_REDUCTION: 16
  ACT_MODE: silu # change activation
  OUT_CONV: True
SOLVER:
  NAME: Lamb
  BASE_LR: 0.0032
  SAMPLES_PER_BATCH: 8
  ITERATION_TOTAL: 5
  ITERATION_SAVE: 5
  TEST_EVERY: 5
DATASET:
  DATA_DIR: /data/muhin/Ilyama4k
  DATA_TRAIN: ['MyData']
  DATA_TEST: ['MyData']
  DATA_VAL: ['MyData']